<?php

namespace ContainerMst0CWN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxVkSevService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.wxVkSev' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wxVkSev'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DemoController::delete' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'App\\Controller\\DemoController::edit' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'App\\Controller\\DemoController::index' => ['privates', '.service_locator.o0ZmMkx', 'get_ServiceLocator_O0ZmMkxService', true],
            'App\\Controller\\DemoController::show' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DemoController:delete' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'App\\Controller\\DemoController:edit' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'App\\Controller\\DemoController:index' => ['privates', '.service_locator.o0ZmMkx', 'get_ServiceLocator_O0ZmMkxService', true],
            'App\\Controller\\DemoController:show' => ['privates', '.service_locator.6CuhHSf', 'get_ServiceLocator_6CuhHSfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DemoController::delete' => '?',
            'App\\Controller\\DemoController::edit' => '?',
            'App\\Controller\\DemoController::index' => '?',
            'App\\Controller\\DemoController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DemoController:delete' => '?',
            'App\\Controller\\DemoController:edit' => '?',
            'App\\Controller\\DemoController:index' => '?',
            'App\\Controller\\DemoController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
