<?php

namespace ContainerMst0CWN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O0ZmMkxService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.o0ZmMkx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o0ZmMkx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demoRepository' => ['privates', 'App\\Repository\\DemoRepository', 'getDemoRepositoryService', true],
        ], [
            'demoRepository' => 'App\\Repository\\DemoRepository',
        ]);
    }
}
