<?php

namespace ContainerXpmbRPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemoService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6CuhHSf.App\Entity\Demo' shared service.
     *
     * @return \App\Entity\Demo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6CuhHSf": it references class "App\\Entity\\Demo" but no such service exists.');
    }
}
