<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMst0CWN\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMst0CWN/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMst0CWN.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMst0CWN\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerMst0CWN\App_KernelTestDebugContainer([
    'container.build_hash' => 'Mst0CWN',
    'container.build_id' => '3a2e3289',
    'container.build_time' => 1669895160,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMst0CWN');
