<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpmbRPd\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpmbRPd/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXpmbRPd.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXpmbRPd\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXpmbRPd\App_KernelTestDebugContainer([
    'container.build_hash' => 'XpmbRPd',
    'container.build_id' => '2209525e',
    'container.build_time' => 1669893902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpmbRPd');
