<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKz25LrH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKz25LrH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKz25LrH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKz25LrH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKz25LrH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kz25LrH',
    'container.build_id' => 'b8f61956',
    'container.build_time' => 1669904219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKz25LrH');
