<?php

namespace ContainerKz25LrH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6CuhHSfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6CuhHSf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6CuhHSf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demo' => ['privates', '.errored..service_locator.6CuhHSf.App\\Entity\\Demo', NULL, 'Cannot autowire service ".service_locator.6CuhHSf": it references class "App\\Entity\\Demo" but no such service exists.'],
        ], [
            'demo' => 'App\\Entity\\Demo',
        ]);
    }
}
